name:                ck2hs
version:             0.1.0.0
github:              "githubuser/tarkowsky"
license:             MIT

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ck2hs#readme>

dependencies:
- base >= 4.7 && < 5
- array
- bytestring
- directory
- containers
- mtl
- transformers
#- cereal
- hex
- datetime
- fsnotify
- random
- stm

library:
  source-dirs: src

executables:
  ck2hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ck2hs

tests:
  ck2hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ck2hs
